=== NtreevSoft/CremaResource/tables/Export/ProjectInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Export/ProjectInfo" xmlns="http://schemas.ntreev.com/crema/tables/Export/ProjectInfo" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Export/ProjectInfo" version="3.5" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProjectInfo.ExportInfo.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo CreatedDateTime="2017-10-25T08:34:43.9802704Z" />
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-25T08:35:20.4375344Z" />
        <TableInfo ID="a9ca9738-2c3f-41a3-b380-98987977e42e" />
        <TableInfo CategoryPath="/Export/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TableName" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:35:02.2167024Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:35:15.1647252Z" />
            <ColumnInfo ID="ebc4c3d9-660b-4cb6-a2b7-7949b8f2ef5e" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="FileName" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:35:20.4375344Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:35:20.4375344Z" />
            <ColumnInfo ID="5b908227-2057-4bdd-9801-dd49b5aedcd2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:complexType name="ProjectInfo.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-25T08:34:39.8150631Z" />
        <TableInfo ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca" />
        <TableInfo CategoryPath="/Export/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TableName" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T04:10:42.8835333Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:35:49.235185Z" />
            <ColumnInfo ID="4819b80e-b28d-4a6e-84a3-03dce3fcf599" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProjectPath" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:25:15.4372718Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:35:47.4723819Z" />
            <ColumnInfo ID="fd83f5d6-3ae5-4889-8731-6228262ce181" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element default="Resources" name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T04:15:20.9394109Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T04:16:39.7009661Z" />
            <ColumnInfo ID="6355b338-71f4-4d66-938c-32de1a81c433" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ExportInfo" type="ProjectInfo.ExportInfo.Table" />
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
    <xs:attribute name="RelationID" type="xs:string" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ProjectInfo" type="ProjectInfo.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="ProjectInfo.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Creator" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.Count" type="xs:int" use="optional" />
      <xs:attribute name="ProjectInfo.ID" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Creator" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Count" type="xs:int" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.ID" type="xs:string" use="optional" />
      <xs:attribute name="Creator" type="xs:string" use="optional">
        <xs:annotation>
          <xs:documentation>xml 문서를 생성한 사람의 이름을 설정합니다. 이 값은 선택적입니다.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="CreatedDateTime" type="xs:dateTime" use="optional">
        <xs:annotation>
          <xs:documentation>xml 문서를 생성한 시간을 설정합니다. 이 값은 선택적입니다.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key name="ProjectInfo.Key">
      <xs:selector xpath="t:ProjectInfo" />
      <xs:field xpath="t:ProjectPath" />
    </xs:key>
    <xs:key name="ProjectInfo.ExportInfo.Key">
      <xs:selector xpath="t:ProjectInfo/t:ExportInfo" />
      <xs:field xpath="t:TableName" />
    </xs:key>
  </xs:element>
</xs:schema>

=== NtreevSoft/CremaResource/tables/Export/ProjectInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="3.5"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/Export/ProjectInfo ProjectInfo.xsd"
  ProjectInfo.Modifier="admin"
  ProjectInfo.ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
  ProjectInfo.Count="5"
  ProjectInfo.ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca"
  ProjectInfo.ExportInfo.ID="a9ca9738-2c3f-41a3-b380-98987977e42e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Export/ProjectInfo">
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-25T04:14:12.2163323Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
    RelationID="1be12bf899f70ed89c8fca12d709c2b7">
    <ProjectPath>sub-modules/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-25T04:54:50.2168264Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
    RelationID="0d9be3dd1b93b1f4e9d70fb489257e9a">
    <ProjectPath>client/Ntreev.Crema.Client.SmartSet/Properties</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-25T05:56:39.2096651Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
    RelationID="2b63edd87b6adbc62a67f72ba6729c45">
    <ProjectPath>client/Ntreev.Crema.Client.Common/Properties</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-25T06:49:12.8559905Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
    RelationID="4000645526cc7eab95d6c5d1798d8d4a">
    <ProjectPath>client/Ntreev.Crema.Client.Tables/Properties</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-25T07:59:28.3201544Z"
    Modifier="admin"
    ModifiedDateTime="2017-10-25T08:34:43.9958704Z"
    RelationID="890844504c4f92abbf20a513d8d6c79b">
    <ProjectPath>common/Ntreev.Crema.Presentation/Properties</ProjectPath>
  </ProjectInfo>
</Content>
