=== NtreevSoft/CremaResource/tables/Templates/ProjectInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:t="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" elementFormDefault="qualified" targetNamespace="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo" version="3.5" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="../../types/ProjectType.xsd" namespace="http://schemas.ntreev.com/crema/types/ProjectType" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProjectInfo.ExportInfo.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo CreatedDateTime="2017-10-25T08:34:43.9802704Z" />
        <TableInfo ModifiedDateTime="2017-10-26T08:06:01.8025991Z" />
        <TableInfo ID="a9ca9738-2c3f-41a3-b380-98987977e42e" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ID" type="xs:int">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-26T06:21:11.8559514Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-26T06:21:41.9328042Z" />
            <ColumnInfo AutoIncrement="true" />
            <ColumnInfo ID="2bc9175c-512b-4f9d-8545-f73e21760840" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element default="Properties/Resources.resx" name="FileName" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:35:20.4375344Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-26T08:42:54.0424847Z" />
            <ColumnInfo ID="5b908227-2057-4bdd-9801-dd49b5aedcd2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="TableName" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:35:02.2167024Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-26T06:20:29.0650763Z" />
            <ColumnInfo ID="ebc4c3d9-660b-4cb6-a2b7-7949b8f2ef5e" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:complexType name="ProjectInfo.Table">
    <xs:annotation>
      <xs:appinfo>
        <TableInfo Modifier="admin" />
        <TableInfo ModifiedDateTime="2017-10-26T08:06:01.8181991Z" />
        <TableInfo ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca" />
        <TableInfo CategoryPath="/Templates/" />
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ProjectType" xmlns:q1="http://schemas.ntreev.com/crema/types/ProjectType" type="q1:ProjectType">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:40:56.9613255Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:42:23.9002782Z" />
            <ColumnInfo ID="53fd6271-0121-4f55-be26-7a47e64beebd" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="Name" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:38:54.29831Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:42:24.92988Z" />
            <ColumnInfo ID="e8680af2-37c8-4719-bc81-6b2296952bc2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProjectPath" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <ColumnInfo Creator="admin" />
            <ColumnInfo CreatedDateTime="2017-10-25T08:25:15.4372718Z" />
            <ColumnInfo Modifier="admin" />
            <ColumnInfo ModifiedDateTime="2017-10-25T08:42:25.6942813Z" />
            <ColumnInfo ID="fd83f5d6-3ae5-4889-8731-6228262ce181" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ExportInfo" type="ProjectInfo.ExportInfo.Table" />
    </xs:sequence>
    <xs:attribute default="" name="Creator" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="CreatedDateTime" type="xs:dateTime" />
    <xs:attribute default="" name="Modifier" type="xs:string" />
    <xs:attribute default="0001-01-01T00:00:00" name="ModifiedDateTime" type="xs:dateTime" />
    <xs:attribute default="All" name="Tags" type="xs:string" use="optional" />
    <xs:attribute default="true" name="Enable" type="xs:boolean" use="optional" />
    <xs:attribute name="RelationID" type="xs:string" />
  </xs:complexType>
  <xs:element name="Content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ProjectInfo" type="ProjectInfo.Table" />
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" use="required" />
      <xs:attribute name="ProjectInfo.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Creator" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.Count" type="xs:int" use="optional" />
      <xs:attribute name="ProjectInfo.ID" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.CreatedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Creator" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.ModifiedDateTime" type="xs:dateTime" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Modifier" type="xs:string" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.Count" type="xs:int" use="optional" />
      <xs:attribute name="ProjectInfo.ExportInfo.ID" type="xs:string" use="optional" />
      <xs:attribute name="Creator" type="xs:string" use="optional">
        <xs:annotation>
          <xs:documentation>xml 문서를 생성한 사람의 이름을 설정합니다. 이 값은 선택적입니다.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="CreatedDateTime" type="xs:dateTime" use="optional">
        <xs:annotation>
          <xs:documentation>xml 문서를 생성한 시간을 설정합니다. 이 값은 선택적입니다.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
    <xs:key name="ProjectInfo.Key">
      <xs:selector xpath="t:ProjectInfo" />
      <xs:field xpath="t:ProjectType" />
      <xs:field xpath="t:Name" />
    </xs:key>
    <xs:key name="ProjectInfo.ExportInfo.Key">
      <xs:selector xpath="t:ProjectInfo/t:ExportInfo" />
      <xs:field xpath="t:ID" />
    </xs:key>
  </xs:element>
</xs:schema>

=== NtreevSoft/CremaResource/tables/Templates/ProjectInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="3.5"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo ProjectInfo.xsd"
  ProjectInfo.Modifier="admin"
  ProjectInfo.ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
  ProjectInfo.Count="7"
  ProjectInfo.ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca"
  ProjectInfo.ExportInfo.Modifier="admin"
  ProjectInfo.ExportInfo.ModifiedDateTime="2017-10-31T23:53:54.9465845Z"
  ProjectInfo.ExportInfo.Count="5"
  ProjectInfo.ExportInfo.ID="a9ca9738-2c3f-41a3-b380-98987977e42e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo">
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4202267Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="415f7e9d783caab07d757277ad1004f5">
    <KindType>Client</KindType>
    <Name>Ntreev.Crema.Client.SmartSet</Name>
    <ProjectPath>client/Ntreev.Crema.Client.SmartSet/Ntreev.Crema.Client.SmartSet.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:53:14.4212452Z"
      ModifiedDateTime="2017-10-31T06:53:14.4212452Z">
      <ID>1</ID>
      <FileName />
      <TableName>ClientSmartSet</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4202267Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="12335022f6c40f80a1d60fed1216fee2">
    <KindType>Client</KindType>
    <Name>Ntreev.Crema.Client.Common</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Common/Ntreev.Crema.Client.Common.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:53:14.4212452Z"
      ModifiedDateTime="2017-10-31T06:53:14.4212452Z">
      <ID>2</ID>
      <FileName />
      <TableName>ClientCommon</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="e9bf26bd43c00da6d59b2991e893384e">
    <KindType>Client</KindType>
    <Name>Ntreev.Crema.Client.Tables</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Tables/Ntreev.Crema.Client.Tables.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="43739410bb3bdaa77399dc0ddf1660a2">
    <KindType>Common</KindType>
    <Name>Ntreev.Crema.Presentation</Name>
    <ProjectPath>common/Ntreev.Crema.Presentation/Ntreev.Crema.Presentation.csproj</ProjectPath>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="87ec3c57e41e0c1e70b5df0fc86b0b47">
    <KindType>SubModule</KindType>
    <Name>Ntreev.ModernUI.Framework</Name>
    <ProjectPath>sub-modules/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:53:14.4212452Z"
      ModifiedDateTime="2017-10-31T06:53:14.4212452Z">
      <ID>0</ID>
      <FileName />
      <TableName>ModernUIFramework</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:53:14.4212452Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="d033476fdf69a1f39f78e8a9e9006262">
    <KindType>Client</KindType>
    <Name>Ntreev.Crema.Client.Converters</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Converters/Ntreev.Crema.Client.Converters.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:53:14.4212452Z"
      ModifiedDateTime="2017-10-31T06:53:14.4212452Z">
      <ID>3</ID>
      <FileName />
      <TableName>ClientConverters</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    Creator="admin"
    CreatedDateTime="2017-10-31T23:53:46.2885692Z"
    Modifier="admin"
    ModifiedDateTime="2017-11-01T08:22:24.7493264Z"
    RelationID="e6e45179544e5a3dce1d8cf66c9f3ca1">
    <KindType>Client</KindType>
    <Name>Ntreev.Crema.Client.Console</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Console/Ntreev.Crema.Client.Console.csproj</ProjectPath>
    <ExportInfo
      Creator="admin"
      CreatedDateTime="2017-10-31T23:53:54.9465845Z"
      Modifier="admin"
      ModifiedDateTime="2017-10-31T23:53:54.9465845Z">
      <ID>4</ID>
      <FileName />
      <TableName>ClientConsole</TableName>
    </ExportInfo>
  </ProjectInfo>
</Content>

=== NtreevSoft/CremaResource/tables/Export/CremaProjectInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Content
  Version="3.5"
  xsi:schemaLocation="http://schemas.ntreev.com/crema/tables/Export/CremaProjectInfo ../Templates/ProjectInfo.xsd"
  ProjectInfo.ModifiedDateTime="2017-10-31T06:48:14.6123738Z"
  ProjectInfo.Count="8"
  ProjectInfo.ID="dea31cbb-0fbd-40b7-9e09-bf11038a3aca"
  ProjectInfo.ExportInfo.Count="8"
  ProjectInfo.ExportInfo.ID="a9ca9738-2c3f-41a3-b380-98987977e42e" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.ntreev.com/crema/tables/Templates/ProjectInfo">
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6113731Z"
    ModifiedDateTime="2017-10-31T06:48:14.6113731Z"
    RelationID="415f7e9d783caab07d757277ad1004f5">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.SmartSet</Name>
    <ProjectPath>client/Ntreev.Crema.Client.SmartSet/Ntreev.Crema.Client.SmartSet.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6193786Z"
      ModifiedDateTime="2017-10-31T06:48:14.6193786Z">
      <ID>1</ID>
      <FileName />
      <TableName>ClientSmartSet</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6113731Z"
    ModifiedDateTime="2017-10-31T06:48:14.6113731Z"
    RelationID="12335022f6c40f80a1d60fed1216fee2">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.Common</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Common/Ntreev.Crema.Client.Common.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6213826Z"
      ModifiedDateTime="2017-10-31T06:48:14.6213826Z">
      <ID>2</ID>
      <FileName />
      <TableName>ClientCommon</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6118736Z"
    ModifiedDateTime="2017-10-31T06:48:14.6118736Z"
    RelationID="e9bf26bd43c00da6d59b2991e893384e">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.Tables</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Tables/Ntreev.Crema.Client.Tables.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6218804Z"
      ModifiedDateTime="2017-10-31T06:48:14.6218804Z">
      <ID>4</ID>
      <FileName />
      <TableName>ClientTables</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6118736Z"
    ModifiedDateTime="2017-10-31T06:48:14.6118736Z"
    RelationID="43739410bb3bdaa77399dc0ddf1660a2">
    <ProjectType>Common</ProjectType>
    <Name>Ntreev.Crema.Presentation</Name>
    <ProjectPath>common/Ntreev.Crema.Presentation/Ntreev.Crema.Presentation.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6218804Z"
      ModifiedDateTime="2017-10-31T06:48:14.6218804Z">
      <ID>5</ID>
      <FileName />
      <TableName>CommonPresentation</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6118736Z"
    ModifiedDateTime="2017-10-31T06:48:14.6118736Z"
    RelationID="87ec3c57e41e0c1e70b5df0fc86b0b47">
    <ProjectType>SubModule</ProjectType>
    <Name>Ntreev.ModernUI.Framework</Name>
    <ProjectPath>sub-modules/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework/Ntreev.ModernUI.Framework.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6218804Z"
      ModifiedDateTime="2017-10-31T06:48:14.6218804Z">
      <ID>0</ID>
      <FileName />
      <TableName>ModernUIFramework</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6118736Z"
    ModifiedDateTime="2017-10-31T06:48:14.6118736Z"
    RelationID="d033476fdf69a1f39f78e8a9e9006262">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.Converters</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Converters/Ntreev.Crema.Client.Converters.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6218804Z"
      ModifiedDateTime="2017-10-31T06:48:14.6218804Z">
      <ID>3</ID>
      <FileName />
      <TableName>ClientConverters</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6123738Z"
    ModifiedDateTime="2017-10-31T06:48:14.6123738Z"
    RelationID="7db47cc536bb01b0be5d91233da11ea1">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.Types</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Types/Ntreev.Crema.Client.Types.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6223809Z"
      ModifiedDateTime="2017-10-31T06:48:14.6223809Z">
      <ID>6</ID>
      <FileName />
      <TableName>ClientTypes</TableName>
    </ExportInfo>
  </ProjectInfo>
  <ProjectInfo
    CreatedDateTime="2017-10-31T06:48:14.6123738Z"
    ModifiedDateTime="2017-10-31T06:48:14.6123738Z"
    RelationID="e6d11746991707aed6074138a306d52f">
    <ProjectType>Client</ProjectType>
    <Name>Ntreev.Crema.Client.Framework</Name>
    <ProjectPath>client/Ntreev.Crema.Client.Framework/Ntreev.Crema.Client.Framework.csproj</ProjectPath>
    <ExportInfo
      CreatedDateTime="2017-10-31T06:48:14.6223809Z"
      ModifiedDateTime="2017-10-31T06:48:14.6223809Z">
      <ID>7</ID>
      <FileName />
      <TableName>ClientFramework</TableName>
    </ExportInfo>
  </ProjectInfo>
</Content>
